# 1.0 Introduction to Camelot
https://www.youtube.com/watch?v=reldH-VubfY

## 1.1 Install to use Camelot

In [1]:
# !pip install "camelot-py[cv]" -q

In [3]:
# !pip install ghostscript

Requirement already satisfied: ghostscript in c:\users\user\anaconda3\lib\site-packages (0.7)
Requirement already satisfied: setuptools>=38.6.0 in c:\users\user\anaconda3\lib\site-packages (from ghostscript) (61.2.0)

In [28]:
# !pip install camelot-py[plot]

Requirement already satisfied: camelot-py[plot] in c:\users\user\anaconda3\lib\site-packages (0.10.1)
Requirement already satisfied: openpyxl>=2.5.8 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (3.0.9)
Requirement already satisfied: click>=6.7 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (8.0.4)
Requirement already satisfied: tabulate>=0.8.9 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (0.8.9)
Requirement already satisfied: pdfminer.six>=20200726 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (20221105)
Requirement already satisfied: PyPDF2>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (2.12.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (1.21.5)
Requirement already satisfied: pandas>=0.23.4 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (1.4.2)
Requirement already satisfied: chardet>=3.0.4 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (4.0.0)
Requirement already satisfied: matplotlib>=2.2.3 in c:\users\user\anaconda3\lib\site-packages (from camelot-py[plot]) (3.5.1)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from click>=6.7->camelot-py[plot]) (0.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (3.0.4)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (1.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2.3->camelot-py[plot]) (9.0.1)
Requirement already satisfied: et-xmlfile in c:\users\user\anaconda3\lib\site-packages (from openpyxl>=2.5.8->camelot-py[plot]) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.23.4->camelot-py[plot]) (2021.3)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from pdfminer.six>=20200726->camelot-py[plot]) (2.0.4)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\user\anaconda3\lib\site-packages (from pdfminer.six>=20200726->camelot-py[plot]) (38.0.4)
Requirement already satisfied: typing_extensions>=3.10.0.0 in c:\users\user\anaconda3\lib\site-packages (from PyPDF2>=1.26.0->camelot-py[plot]) (4.1.1)
Requirement already satisfied: cffi>=1.12 in c:\users\user\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[plot]) (1.15.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2.3->camelot-py[plot]) (1.16.0)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[plot]) (2.21)

## 1.2 Why Camelot

#### Why choose flavor 'stream' instead of 'lattice'?
- To detect line segments, Lattice needs the lines that make the table to be in the foreground
- Not all tables have obvious line segments
- Attributes like 'columns' and 'table_areas' can *only* be used with 'stream'
***
Reference:
https://camelot-py.readthedocs.io/en/master/user/advanced.html

#### Comparison with other Tools
https://github.com/camelot-dev/camelot/wiki/Comparison-with-other-PDF-Table-Extraction-libraries-and-tools

# 2.0 Extraction of Table Data

***
References:
- https://www.tutorialspoint.com/matplotlib-how-to-show-the-coordinates-of-a-point-upon-mouse-click
- https://stackoverflow.com/questions/33998802/get-list-of-pdf-files-in-folder
- https://www.codespeedy.com/how-to-count-the-number-of-pages-in-a-pdf-file-in-python/#:~:text=The%20'PdfFileReader()'%20is%20an,function%20will%20display%20the%20result
- https://xlsxwriter.readthedocs.io/example_pandas_multiple.html

In [85]:
import camelot as cam
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import PyPDF2
import os
from os import path

## 2.1 Basic Extraction

Steps for Basic Extraction:
1) Place all pdfs for extraction in the same directory as this jupyter notebook
2) Run the cell below
3) The output will be excel files of the same name in the same directory as this jupyter notebook

In [86]:
# get all files in the same directory
files = [f for f in os.listdir('.') if os.path.isfile(f) and f.endswith('.pdf')]

for file_name in files:
    file_dict = {}
    # get the number of pages each pdf has
    file = open(file_name, 'rb')
    readpdf = PyPDF2.PdfFileReader(file)
    totalpages = readpdf.numPages
    
    # let camelot read each page
    for num_page in range(1, totalpages+1):
        file_dict[file_name[0:-4] + "_page_" + str(num_page)] = cam.read_pdf(file_name, flavor='stream', pages=str(num_page), edge_tol=500)

    # 1 pdf file = 1 excel file
    # if pdf have more than 1 page, excel file will have the same number of sheets
    # eg. if pdf has 2 pages, excel has 2 sheets
    writer = pd.ExcelWriter(file_name[0:-4] + '.xlsx', engine='xlsxwriter')

    for k,v in file_dict.items():
        for i in range(len(file_dict[k])):
            file_dict[k][i].df.to_excel(writer, sheet_name= k[-6:] + "_" + "table_" + str(i+1))

    writer.close()

C:\Users\User\anaconda3\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")
C:\Users\User\anaconda3\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")
C:\Users\User\anaconda3\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")
C:\Users\User\anaconda3\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")
C:\Users\User\anaconda3\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")
C:\Users\User\anaconda3\lib\site-packages\camelot\parsers\stream.py:448: UserWarning: page-39 is image-based, camelot only works on text-based pages.
  warnings.warn(

<b>Testing</b> a new python library for financial statement analysis...

- https://levelup.gitconnected.com/replace-excel-with-python-for-financial-statement-analysis-855f6cc7305a
- https://timokats.github.io/fibooksdocs/
- https://github.com/TimoKats/fibooks/blob/977e71dcdbe87e68162cc415f59ee720af4bc0fe/demo/demo.ipynb

In [92]:
# !pip install fibooks

Collecting fibooks
  Using cached fibooks-2.0.4.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: openpyxl in c:\users\user\anaconda3\lib\site-packages (from fibooks) (3.0.10)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (from fibooks) (1.5.2)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from fibooks) (65.6.3)
Requirement already satisfied: et_xmlfile in c:\users\user\anaconda3\lib\site-packages (from openpyxl->fibooks) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas->fibooks) (2022.7)
Requirement already satisfied: numpy>=1.20.3 in c:\users\user\anaconda3\lib\site-packages (from pandas->fibooks) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\user\anaconda3\lib\site-packages (from pandas->fibooks) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->fibooks) (1.16.0)
Building wheels for collected packages: fibooks
  Building wheel for fibooks (setup.py): started
  Building wheel for fibooks (setup.py): finished with status 'done'
  Created wheel for fibooks: filename=fibooks-2.0.4-py3-none-any.whl size=7223 sha256=50207c325b7534275eda45f59c0a253e9331ce539b57b5ffb5734bafb534f37f
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\dd\1e\80\170fdd8d354b11d6596bd779be147a1999f1fd69bf0a8dd6df
Successfully built fibooks
Installing collected packages: fibooks
Successfully installed fibooks-2.0.4

In [93]:
import fibooks
from fibooks import balance_sheet
from fibooks import income_statement
from fibooks import statement_of_cashflows
from fibooks import other

# other libraries (that are integrated with fibooks)
import pandas as pd
import seaborn as sns
from sklearn import tree
import matplotlib.pyplot as plt

In [106]:
nikon_q1fy2023 = income_statement('nikon corporation')
nikon_q1fy2023.load_excel('edited/q1fy2023-financial-data.xlsx')
pd.set_option('display.max_columns', None)
nikon_q1fy2023.content

,corporate total revenue,corporate total operating profit,profit before income taxes,profit attributable to owners of the parent,imaging products business,imaging products business operating profit,precision equipment business,precision equipment business operating profit,healthcare business,healthcare business operating profit,components business,components business operating profit,industrial metrology and others,industrial metrology and others operating profit,corporate profit (loss) non-attributable to any reportable segments,us$,euro,digital camera-interchangeable lens type,interchangeable lens,compact dsc,fpd lithography systems,semiconductor,lithography systems,5g/6g,7g/8g,10.5g,"i-line, etc.",krf,arf,arf imm.,imaging products business revenue,precision equipment business revenue,healthcare business revenue,components business revenue,industrial metrology and others revenue,new products,refurbished products
0,132.2,19.9,21.1,15.8,50.0,9.2,51.8,13.4,15.8,0.4,7.7,2.1,6.7,-1.0,-4.3,110.0,132.0,220.0,390.0,70.0,13.0,0.0,1.0,6.0,1.0,6.0,0.0,1.0,0.0,0.0,50.0,51.8,15.8,7.7,6.7,0.0,1.0
1,273.0,32.1,35.9,26.4,89.2,12.5,119.2,27.5,33.0,0.9,16.7,3.4,14.6,-1.6,-10.7,110.0,131.0,390.0,660.0,130.0,30.0,6.0,9.0,16.0,1.0,13.0,11.0,3.0,0.0,1.0,89.2,119.2,33.0,16.7,14.6,6.0,9.0
2,539.6,49.9,57.0,42.6,178.2,19.0,211.2,39.4,73.2,4.3,40.8,12.7,36.0,2.9,-28.6,112.0,131.0,700.0,1270.0,190.0,46.0,17.0,18.0,30.0,1.0,15.0,24.0,5.0,3.0,3.0,178.2,211.2,73.2,40.8,36.0,17.0,18.0
3,145.6,15.3,16.5,11.8,61.2,13.6,41.4,4.0,21.7,0.8,12.9,5.4,8.1,0.6,-9.2,130.0,138.0,200.0,340.0,40.0,7.0,4.0,4.0,4.0,0.0,3.0,4.0,3.0,1.0,0.0,61.2,41.4,21.7,12.9,8.1,4.0,4.0
4,295.0,23.0,24.0,17.0,100.0,13.0,115.0,13.0,38.0,3.0,26.0,8.0,16.0,1.0,-15.0,120.0,130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,115.0,38.0,26.0,16.0,0.0,0.0
5,275.0,23.0,24.0,17.0,105.0,18.0,90.0,8.0,38.0,3.0,26.0,8.0,16.0,1.0,-15.0,125.0,134.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.0,90.0,38.0,26.0,16.0,0.0,0.0
6,620.0,50.0,52.0,38.0,210.0,22.0,240.0,35.0,80.0,6.0,53.0,17.0,37.0,4.0,-34.0,120.0,130.0,700.0,1250.0,100.0,31.0,39.0,22.0,17.0,6.0,8.0,32.0,8.0,11.0,10.0,210.0,240.0,80.0,53.0,37.0,39.0,22.0
7,625.0,55.0,57.0,42.0,215.0,27.0,240.0,35.0,80.0,6.0,53.0,17.0,37.0,4.0,-34.0,122.0,132.0,700.0,1250.0,100.0,31.0,39.0,22.0,17.0,6.0,8.0,32.0,8.0,11.0,10.0,215.0,240.0,80.0,53.0,37.0,39.0,22.0

## 2.2 Advanced Extraction

If output from Basic Extraction is very inaccurate, user can choose to use Advanced Extraction which works by clicking coordinates on a pop out window.
- To identify table area: click top left then bottom right corners of the table
- To identify columns: click the spaces between the columns

<b>Step 1</b>: Input file name (file has to be in the same folder)

In [110]:
file_dict = {}
file_name = input("What is the file name? ")

What is the file name? q4fy2022-financial-data.pdf

<b>Step 2</b>: User inputs a page number, number of tables user would like to identify, number of columns for each table identified. 
<br> If user would like to repeat for other pages, repeat step 2 & 3 only. Do not repeat step 1.

<b>Step 3</b>: Click the coordinates for the table(s), then coordinates for the columns.
<br> If there is more than 1 table, click top left and bottom right for all tables first, followed by the coordinates of the columns for all tables in order of table 1,2,3,... (i.e. click column coordinates for table 1, then do the same for table 2, then table 3 and so on)

In [112]:
num_page = input("Page number? ")

num_columns_for_table = []
total_columns_count = 0
num_tables = int(input("How many tables? "))

# get number of columns for each table
for i in range(1, num_tables+1):
    num_columns = int(input("How many columns for table " + str(i) + "? "))
    num_columns_for_table.append(num_columns)
    total_columns_count += num_columns
    
table_coords = []
column_coords = []

file_dict[file_name[0:-4] + "_page_" + str(num_page)] = cam.read_pdf(file_name, flavor='stream', pages=str(num_page))

%matplotlib tk
def get_table_coords(event):
    table_coords.append((event.xdata, event.ydata))
    print('x: {} and y: {}'.format(event.xdata, event.ydata))

    if len(table_coords) == num_tables*2:
        print("table_coords", table_coords)

        print("\nPress space between columns.")
        print("Column Coordinates:")
        cid_column = fig.canvas.mpl_connect('button_press_event', get_column_coords)


def get_column_coords(event):
    column_coords.append(event.xdata)
    print('x: {}'.format(event.xdata))

    if len(column_coords) == total_columns_count - num_tables:
        fig.canvas.mpl_disconnect(cid_table)
        plt.close(1)
        mtable_areas = convert_table_coords(table_coords[:num_tables*2])
        print("mtable_areas", mtable_areas)
        print("column_coords", column_coords)
        mcolumns = convert_column_coords(column_coords)
        print("mcolumns", mcolumns)

        file_dict[file_name[0:-4] + "_page_" + str(num_page)] = cam.read_pdf(file_name, flavor='stream', pages=str(num_page), columns=mcolumns, table_areas=mtable_areas)
        print(file_dict)

fig = cam.plot(file_dict[file_name[0:-4] + "_page_" + str(num_page)][0], kind='text')
print("\nFor each table, Press top left of table then bottom right of table.")
print("Table Coordinates:")
cid_table = fig.canvas.mpl_connect('button_press_event', get_table_coords)

# to convert table coordinates
# FROM: [(59.607077633406675, 906.6078216799116), (728.027135672406, 535.9119816320824), (59.607077633406675, 515.4799274562178), (736.7837303192049, 57.21814094039733)]
# TO: '59.607077633406675, 906.6078216799116, 728.027135672406, 535.9119816320824', '59.607077633406675, 515.4799274562178, 736.7837303192049, 57.21814094039733'
def convert_table_coords(table_coords):
    count = 0
    to_return = []
    new_table_coords = ""
    for tup in table_coords:
        for num in tup:
            if count % 4 == 0 and count != 0:
                new_table_coords = new_table_coords[:-2]
                to_return.append(new_table_coords)
                new_table_coords = ""
                new_table_coords += str(num) + ", "
                count += 1
            else:
                new_table_coords += str(num) + ", "
                count += 1
    new_table_coords = new_table_coords[:-2]
    to_return.append(new_table_coords)
    return to_return
        
# to convert column coordinates
# FROM:[135.4975645723323, 246.41443009845443, 304.79172774378196, 374.8444849181749, 447.81610697483427, 509.1122695024279, 561.6518373832226, 622.9479999108165, 678.4064326738775, 243.49556521618808, 316.46718727284747, 383.60107956497393, 447.81610697483427, 506.1934046201617, 564.5707022654891, 620.0291350285501, 681.3252975561439]
# TO: '135.4975645723323, 246.41443009845443, 304.79172774378196, 374.8444849181749, 447.81610697483427, 509.1122695024279, 561.6518373832226, 622.9479999108165, 678.4064326738775', '243.49556521618808, 316.46718727284747, 383.60107956497393, 447.81610697483427, 506.1934046201617, 564.5707022654891, 620.0291350285501, 681.3252975561439'
def convert_column_coords(column_coords):
    count = 0
    to_return = []
    count_for_table = 0
    new_column_coords = ""
    for num in column_coords:
        if count == num_columns_for_table[count_for_table]-1:
            new_column_coords = new_column_coords[:-2]
            to_return.append(new_column_coords)
            new_column_coords = ""
            new_column_coords += str(num) + ", "
            count += 1
            count_for_table += 1
        else:
            new_column_coords += str(num) + ", "
            count += 1
    new_column_coords = new_column_coords[:-2]
    to_return.append(new_column_coords)
    return to_return

Page number? 2
How many tables? 2
How many columns for table 1? 7
How many columns for table 2? 6

For each table, Press top left of table then bottom right of table.
Table Coordinates:
x: 52.78364402020267 and y: 818.4131082828283
x: 521.1686399797986 and y: 438.58830063492076
x: 53.76764611255476 and y: 433.66829017316024
x: 521.1686399797986 and y: 285.0839742279943
table_coords [(52.78364402020267, 818.4131082828283), (521.1686399797986, 438.58830063492076), (53.76764611255476, 433.66829017316024), (521.1686399797986, 285.0839742279943)]

Press space between columns.
Column Coordinates:
x: 119.69578630014496 and y: 771.1810078499279
x: 119.69578630014496
x: 204.31996624242487 and y: 769.2130036652236
x: 204.31996624242487
x: 264.3440938759025 and y: 764.2929932034633
x: 264.3440938759025
x: 319.44821104761974 and y: 764.2929932034633
x: 319.44821104761974
x: 381.4403428658015 and y: 764.2929932034633
x: 381.4403428658015
x: 443.43247468398334 and y: 758.3889806493507
x: 443.43247468398334
x: 164.95988254834117 and y: 398.24421484848494
x: 164.95988254834117
x: 262.37608969119833 and y: 388.40419392496403
x: 262.37608969119833
x: 317.4802068629155 and y: 386.4361897402598
x: 317.4802068629155
x: 378.4883365887452 and y: 377.580170909091
x: 378.4883365887452
x: 432.60845166811026 and y: 386.4361897402598
x: 432.60845166811026
mtable_areas ['52.78364402020267, 818.4131082828283, 521.1686399797986, 438.58830063492076', '53.76764611255476, 433.66829017316024, 521.1686399797986, 285.0839742279943']
column_coords [119.69578630014496, 204.31996624242487, 264.3440938759025, 319.44821104761974, 381.4403428658015, 443.43247468398334, 164.95988254834117, 262.37608969119833, 317.4802068629155, 378.4883365887452, 432.60845166811026]
mcolumns ['119.69578630014496, 204.31996624242487, 264.3440938759025, 319.44821104761974, 381.4403428658015, 443.43247468398334', '164.95988254834117, 262.37608969119833, 317.4802068629155, 378.4883365887452, 432.60845166811026']
{'q4fy2022-financial-data_page_1': <TableList n=1>, 'q4fy2022-financial-data_page_2': <TableList n=2>}

<b>Step 4</b> (Optional): View the output as dataframe in jupyter

In [113]:
for k,v in file_dict.items():
    for i in range(len(file_dict[k])):
        pd.set_option('display.max_rows', None)
        display(file_dict[k][i].df)

,0,1,2,3,4,5,6,7
0,,"1. Revenue, Operating Profit, Profit before in...",,,,,,
1,,,2021/3,,2022/3,,,2023/3
2,,,,,,,1st Half,Total
3,,,1st Half,Total,1st Half,Total,,
4,,,,,,,Forecast,Forecast
5,,Revenue,175.6,451.2,273.0,539.6,295.0,620.0
6,Corporate,,,,,,,
7,,Operating Profit,-46.6,-56.2,32.1,49.9,23.0,50.0
8,Total,,,,,,,
9,,Profit before income,,,,,,
10,,,-38.8,-45.3,35.9,57.0,24.0,52.0
11,,taxes,,,,,,
12,,Profit attributable to,,,,,,
13,,,-31.5,-34.4,26.4,42.6,17.0,38.0
14,,owners of the parent,,,,,,
15,Imaging Products,Revenue,64.3,150.2,89.2,178.2,100.0,210.0
16,Business,Operating Profit,-27.8,-36.3,12.5,19.0,,
17,,,,,,,13.0,22.0
18,Precision Equipment,Revenue,63.8,184.7,119.2,211.2,115.0,240.0
19,Business,Operating Profit,-7.4,-0.6,21.7,27.7,,
20,,,,,,,13.0,35.0
21,Healthcare,Revenue,25.7,62.8,33.0,73.2,38.0,80.0
22,Business,Operating Profit,-2.3,-3.0,0.9,4.3,,
23,,,,,,,3.0,6.0
24,,Revenue,10.4,25.7,16.7,40.8,26.0,53.0
25,Components,,,,,,,
26,Business,,,,,,,
27,,Operating Profit,-0.9,0.1,3.4,12.7,8.0,17.0
28,Industrial,,,,,,,
29,,Revenue,11.2,27.6,14.6,36.0,16.0,37.0
30,Metrology and,,,,,,,
31,,Operating Profit,-0.5,-1.2,-1.6,2.9,1.0,4.0
32,Others,,,,,,,
33,Corporate profit(loss),,,,,,,
34,non-attributable to any,Operating Profit,-7.4,-15.0,-5.0,-16.9,-15.0,-34.0
35,reportable segments,,,,,,,
36,,● Amounts in this statement are rounded down ...,,,,,,
37,,"● ""Corporate profit (loss) non-attributable t...",,,,,,
38,,"● The ""Components Business"" is newly establis...",,,,,,
39,,"● From FY2023/3, the Next-generation Projects...",,,,,,
40,,"non-attributable to any reportable segments"".",,,,,,
41,2. Exchange Rate (Yen),,,,,,,
42,,,,,,,,Total
43,,,1st Half,Total,1st Half,Total,,
44,,,,,,,,Forecast
45,US$,,107,106,110,112,120,
46,Euro,,121,124,131,131,130,
47,,3. Unit Sales of Nikon Digital Imaging Product...,,,,,,
48,Digital camera-Interchangeable Lens Type,,380,840,390,700,,70
49,Interchangeable Lens,,610,"1,350",660,"1,270",,125
50,Compact DSC,,120,260,130,190,,10
51,,4. Unit Sales of Nikon Lithography Systems（On...,,,,,,
52,FPD Lithography Systems,,5,29,30,46,31,
53,,New Products,6,16,1,9,39,
54,Semiconductor,,,,,,,
55,Lithography Systems,,,,,,22,
56,,Refurbished Products,3,11,9,18,,
57,,Total,9,27,10,27,61,
58,,"● From the forecast of 2023/3, ""New Products""...",,,,,,
59,,5. Unit Sales of Nikon FPD Lithography Systems...,,,,,,
60,,5G/6G,1,11,16,30,,17
61,,7G/8G,0,4,1,1,6,
62,,10.5G,4,14,13,15,8,
63,,6. Unit Sales of Nikon Semiconductor Lithograp...,,,,,,
64,,i-line etc.,1,10,6,16,,32
65,,KrF,2,4,3,5,8,
66,,ArF,4,7,0,3,,11
67,,ArF imm.,2,6,1,3,,10
68,,"● From the forecast of 2023/3, ""i-line etc."" ...",,,,,,

,0,1,2,3,4,5,6
0,,"7. Capital Expenditures, Depreciation & Amorti...",,,,,
1,,,2021/3,,2022/3,,2023/3
2,,,,,,,Total
3,,,1st Half,Total,1st Half,Total,
4,,,,,,,Forecast
5,,Capital Expenditures,14.0,30.5,26.0,42.1,40.0
6,Corporate,,,,,,
7,,Depreciation & Amortization,14.7,28.0,12.1,24.8,27.0
8,Total,,,,,,
9,,R&D Expenditures,29.1,59.9,28.5,61.1,64.0
10,,Capital Expenditures,2.1,6.4,2.3,4.5,-
11,Imaging Products,,,,,,
12,,Depreciation & Amortization,3.4,5.2,1.4,3.0,-
13,Business,,,,,,
14,,R&D Expenditures,8.7,16.9,6.6,15.2,17.0
15,,Capital Expenditures,3.3,7.4,3.1,6.9,-
16,Precision Equipment,,,,,,
17,,Depreciation & Amortization,2.0,4.1,1.8,3.9,-
18,Business,,,,,,
19,,R&D Expenditures,11.8,25.8,14.0,28.6,20.0
20,,Capital Expenditures,0.9,2.5,3.0,4.5,-
21,Healthcare,,,,,,
22,,Depreciation & Amortization,2.2,4.5,2.0,4.1,-
23,Business,,,,,,
24,,R&D Expenditures,2.7,5.8,2.7,6.0,5.5
25,,Capital Expenditures,1.3,2.8,3.2,6.6,
26,Components,,,,,,- -
27,,Depreciation & Amortization,1.1,2.1,1.1,2.3,
28,Business,,,,,,
29,,R&D Expenditures,1.5,3.0,1.1,2.8,4.0
30,,Capital Expenditures,2.1,4.0,3.0,5.6,-
31,Industrial Metrology,,,,,,
32,,Depreciation & Amortization,2.5,4.9,2.5,5.1,-
33,and Others,,,,,,
34,,R&D Expenditures,0.7,1.5,0.7,1.8,2.5
35,,Capital Expenditures,4.0,7.1,11.1,13.8,-
36,Undistributed,,,,,,
37,,Depreciation & Amortization,3.4,7.0,3.0,6.2,-
38,Corporate Divisions,,,,,,
39,,R&D Expenditures,3.7,7.0,3.4,6.4,15.0
40,● Including intangible fixed assets.,,,,,,
41,,● Amounts in this statement are rounded down ...,,,,,
42,,● Due to the change of the reportable segmens...,,,,,
43,,"● From FY2023/3, the Next-generation Projects...",,,,,
44,,"non-attributable to any reportable segments"". ...",,,,,

,0,1,2,3,4,5
0,8. Cash Dividends (yen: interim / year-end),,,,,
1,,2019/3,2020/3,2021/3,2022/3,2023/3 (est.)
2,,30.0 30.0,30.0 10.0,10.0 10 .0,20.0 20.0,20.0 20.0
3,9. Number of Employees,,,,,
4,,2019/3,2020/3,2021/3,2022/3,
5,Consolidated,"20,917","20,190","19,448","18,437",
6,Non-Consolidated *,"4,398","4,442","4,183","4,174",
7,Outside Japan,"12,087","11,408","10,619","9,791",
8,Japan,"8,830","8,782","8,829","8,646",
9,,,＊The figure does not include personnel dispatc...,,,

<b>Step 5</b>: Export the output as an excel file. Each page will be a new sheet in the excel file

In [24]:
writer = pd.ExcelWriter(file_name[0:-4] + '.xlsx', engine='xlsxwriter')

for k,v in file_dict.items():
    for i in range(len(file_dict[k])):
        file_dict[k][i].df.to_excel(writer, sheet_name= k[-6:] + "_" + "table_" + str(i+1))

writer.close()